### ISSUE TITLE
[DIS-611] Improve optimistic application of shared reducers

### ISSUE THREAD

**Issue by paulgb** [drifting-in-space/driftdb#24]
Currently, shared reducers will advance optimistically on the client side, but slide back as states start coming in from the server.

Instead, we should:
- Keep a queue of local messages that have been applied optimistically.
- As messages from the server come in, compare them with the message at the back of the queue.
  - If the back of the queue is an exact match, discard it from the queue
  - If the back of the queue is not an exact match, throw out the queue and roll back and apply it

<sub>[DIS-611](https://linear.app/drifting/issue/DIS-611/improve-optimistic-application-of-shared-reducers)</sub>

**Comment by ProbableTrain** [comment]
Each message could include a `clientMessageId: ${uniqueClientId}-${localMessageCounter}` field for comparison between queue and server messages, since we can't compare payloads for non-idempotent actions.

**Comment by paulgb** [comment]
Good point, I’ll consider that approach as well.
