### ISSUE TITLE
[DIS-715] Implement /room/:room_id/send in driftdb-server

### ISSUE THREAD

**Issue by imartinezortiz** [drifting-in-space/driftdb#48]
Trying to setup a local installation of driftdb-server, I've managed to connect the ui.driftdb.com to the local server but failed to send a POST request to the `http_url` as [described in the documentation](https://driftdb.com/docs/api#messaging-over-http).

Although I'm new to rust, just reviewing https://github.com/drifting-in-space/driftdb/blob/main/driftdb-server/src/server.rs#L207-L212 I understand that there is no route POST `/room/:room_id/send` in the code.

<sub>[DIS-715](https://linear.app/drifting/issue/DIS-715/http-post-roomroom-idsend-not-working-in-driftdb-server)</sub>

**Comment by paulgb** [comment]
As of [driftdb-server](https://crates.io/crates/driftdb-server) 0.1.4, this is now implemented. Thanks for reporting.
