### ISSUE TITLE
A supply-chain security vulnerability found

### ISSUE THREAD

**Issue by ashishbijlani** [drifting-in-space/driftdb#93]
Hi,

I'm a Cybersecurity researcher developing Packj [1]. Our tool has detected a supply-chain vulnerability in this repository. In order for me to disclose it, kindly enable GitHub Private vulnerability reporting, which allows security research to responsibly disclose a security vulnerability.

Thanks!

Packj detects malicious/"risky" NPM/PyPI/Ruby dependencies: https://github.com/ossillate-inc/packj

**Comment by paulgb** [comment]
Hi,

I have enabled this, thank you.

**Comment by ashishbijlani** [comment]
Thanks! Just reported my finding.

**Comment by ashishbijlani** [comment]
Did you get a chance to take a look?
